### PR TITLE
Create blue print classes for Applicant, Role, and Stage

### PR DESCRIPTION
**Pull request by lihaoquan**

### CODE REVIEW

**Review by ChrisHo1341 — APPROVED** [review]

**Comment by ChrisHo1341** [comment]
Are you able to run this version using `./gradlew run`?

**Comment by lihaoquan** [comment]
> Are you able to run this version using `./gradlew run`?

image
I was able to run it through this

**Comment by ChrisHo1341** [comment]
Oh isit because I don't have the other merge? I get this error

image

**Comment by lihaoquan** [comment]
> Oh isit because I don't have the other merge? I get this error
> 
> image

Yes, unfortunately need both merges to work.

**Review by ChrisHo1341 — APPROVED** [review]
Please go ahead

**Pull request merged**
